"""v7

Revision ID: 1856c1868005
Revises: 66cf41f96139
Create Date: 2022-05-22 01:21:15.233193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1856c1868005'
down_revision = '66cf41f96139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('req_ip', sa.String(length=120), nullable=False),
    sa.Column('use_ip', sa.String(length=120), nullable=True),
    sa.Column('token', sa.String(length=96), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('used_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_reset')
    # ### end Alembic commands ###
