"""v11

Revision ID: 43405f2149c7
Revises: 670c99436de6
Create Date: 2022-06-16 01:55:38.482656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43405f2149c7'
down_revision = '670c99436de6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_lock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_lock')
    # ### end Alembic commands ###
