"""v2

Revision ID: bf0e8bc7acb5
Revises: 674823ac9029
Create Date: 2022-05-12 01:11:58.979263

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf0e8bc7acb5'
down_revision = '674823ac9029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('code_ibfk_1', 'code', type_='foreignkey')
    op.drop_column('code', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code', sa.Column('owner_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('code_ibfk_1', 'code', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###
