"""v3

Revision ID: c68e6950ba3f
Revises: bf0e8bc7acb5
Create Date: 2022-05-12 21:04:48.981971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c68e6950ba3f'
down_revision = 'bf0e8bc7acb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code', sa.Column('email', sa.String(length=96), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code', 'email')
    # ### end Alembic commands ###
